-- Deploy structs-pg:cache-trigger-add-queue-20260810-armour-piercing-default-false to pg
--
-- Protobuf JSON omits false booleans, so primaryWeaponArmourPiercing /
-- secondaryWeaponArmourPiercing are often absent from StructType events and
-- jsonb_to_record yields NULL. Coalesce both fields to false so the importer
-- never writes NULL into the columns that
-- table-struct-type-20260810-armour-piercing-default-false makes NOT NULL.
--
-- Body reproduced verbatim from
-- cache-trigger-add-queue-20260612-armour-piercing.sql with only the two
-- SELECT extraction lines changed to COALESCE(..., false).

BEGIN;

    CREATE OR REPLACE FUNCTION cache.handle_event_struct_type(payload jsonb)
    RETURNS void AS
    $BODY$
    DECLARE
        v record;
    BEGIN
        SELECT
            x.id AS id,
            x.type AS type,
            x.category AS category,
            x."buildLimit" AS build_limit,
            x."buildDifficulty" AS build_difficulty,
            x."buildDraw" AS build_draw,
            x."maxHealth" AS max_health,
            x."passiveDraw" AS passive_draw,
            x."possibleAmbit" AS possible_ambit,
            x.movable AS movable,
            x."slotBound" AS slot_bound,
            x."primaryWeapon" AS primary_weapon,
            x."primaryWeaponControl" AS primary_weapon_control,
            x."primaryWeaponCharge" AS primary_weapon_charge,
            x."primaryWeaponAmbits" AS primary_weapon_ambits,
            x."primaryWeaponTargets" AS primary_weapon_targets,
            x."primaryWeaponShots" AS primary_weapon_shots,
            x."primaryWeaponDamage" AS primary_weapon_damage,
            x."primaryWeaponBlockable" AS primary_weapon_blockable,
            x."primaryWeaponCounterable" AS primary_weapon_counterable,
            COALESCE(x."primaryWeaponArmourPiercing", false) AS primary_weapon_armour_piercing,
            x."primaryWeaponRecoilDamage" AS primary_weapon_recoil_damage,
            x."primaryWeaponShotSuccessRateNumerator" AS primary_weapon_shot_success_rate_numerator,
            x."primaryWeaponShotSuccessRateDenominator" AS primary_weapon_shot_success_rate_denominator,
            x."secondaryWeapon" AS secondary_weapon,
            x."secondaryWeaponControl" AS secondary_weapon_control,
            x."secondaryWeaponCharge" AS secondary_weapon_charge,
            x."secondaryWeaponAmbits" AS secondary_weapon_ambits,
            x."secondaryWeaponTargets" AS secondary_weapon_targets,
            x."secondaryWeaponShots" AS secondary_weapon_shots,
            x."secondaryWeaponDamage" AS secondary_weapon_damage,
            x."secondaryWeaponBlockable" AS secondary_weapon_blockable,
            x."secondaryWeaponCounterable" AS secondary_weapon_counterable,
            COALESCE(x."secondaryWeaponArmourPiercing", false) AS secondary_weapon_armour_piercing,
            x."secondaryWeaponRecoilDamage" AS secondary_weapon_recoil_damage,
            x."secondaryWeaponShotSuccessRateNumerator" AS secondary_weapon_shot_success_rate_numerator,
            x."secondaryWeaponShotSuccessRateDenominator" AS secondary_weapon_shot_success_rate_denominator,
            x."passiveWeaponry" AS passive_weaponry,
            x."unitDefenses" AS unit_defenses,
            x."oreReserveDefenses" AS ore_reserve_defenses,
            x."planetaryDefenses" AS planetary_defenses,
            x."planetaryMining" AS planetary_mining,
            x."planetaryRefinery" AS planetary_refinery,
            x."powerGeneration" AS power_generation,
            x."activateCharge" AS activate_charge,
            x."buildCharge" AS build_charge,
            x."defendChangeCharge" AS defend_change_charge,
            x."moveCharge" AS move_charge,
            x."stealthActivateCharge" AS stealth_activate_charge,
            x."attackReduction" AS attack_reduction,
            x."attackCounterable" AS attack_counterable,
            x."stealthSystems" AS stealth_systems,
            x."counterAttack" AS counter_attack,
            x."counterAttackSameAmbit" AS counter_attack_same_ambit,
            x."postDestructionDamage" AS post_destruction_damage,
            x."generatingRate" AS generating_rate,
            x."planetaryShieldContribution" AS planetary_shield_contribution,
            x."oreMiningDifficulty" AS ore_mining_difficulty,
            x."oreRefiningDifficulty" AS ore_refining_difficulty,
            x."unguidedDefensiveSuccessRateNumerator" AS unguided_defensive_success_rate_numerator,
            x."unguidedDefensiveSuccessRateDenominator" AS unguided_defensive_success_rate_denominator,
            x."guidedDefensiveSuccessRateNumerator" AS guided_defensive_success_rate_numerator,
            x."guidedDefensiveSuccessRateDenominator" AS guided_defensive_success_rate_denominator,
            x."triggerRaidDefeatByDestruction" AS trigger_raid_defeat_by_destruction,
            x.class AS class,
            x."classAbbreviation" AS class_abbreviation,
            x."defaultCosmeticModelNumber" AS default_cosmetic_model_number,
            x."defaultCosmeticName" AS default_cosmetic_name
        INTO v
        FROM jsonb_to_record(payload) AS x(
            id integer,
            type text,
            category text,
            "buildLimit" integer,
            "buildDifficulty" integer,
            "buildDraw" integer,
            "maxHealth" integer,
            "passiveDraw" integer,
            "possibleAmbit" integer,
            movable boolean,
            "slotBound" boolean,
            "primaryWeapon" text,
            "primaryWeaponControl" text,
            "primaryWeaponCharge" integer,
            "primaryWeaponAmbits" integer,
            "primaryWeaponTargets" integer,
            "primaryWeaponShots" integer,
            "primaryWeaponDamage" integer,
            "primaryWeaponBlockable" boolean,
            "primaryWeaponCounterable" boolean,
            "primaryWeaponArmourPiercing" boolean,
            "primaryWeaponRecoilDamage" integer,
            "primaryWeaponShotSuccessRateNumerator" integer,
            "primaryWeaponShotSuccessRateDenominator" integer,
            "secondaryWeapon" text,
            "secondaryWeaponControl" text,
            "secondaryWeaponCharge" integer,
            "secondaryWeaponAmbits" integer,
            "secondaryWeaponTargets" integer,
            "secondaryWeaponShots" integer,
            "secondaryWeaponDamage" integer,
            "secondaryWeaponBlockable" boolean,
            "secondaryWeaponCounterable" boolean,
            "secondaryWeaponArmourPiercing" boolean,
            "secondaryWeaponRecoilDamage" integer,
            "secondaryWeaponShotSuccessRateNumerator" integer,
            "secondaryWeaponShotSuccessRateDenominator" integer,
            "passiveWeaponry" text,
            "unitDefenses" text,
            "oreReserveDefenses" text,
            "planetaryDefenses" text,
            "planetaryMining" text,
            "planetaryRefinery" text,
            "powerGeneration" text,
            "activateCharge" integer,
            "buildCharge" integer,
            "defendChangeCharge" integer,
            "moveCharge" integer,
            "stealthActivateCharge" integer,
            "attackReduction" integer,
            "attackCounterable" boolean,
            "stealthSystems" boolean,
            "counterAttack" integer,
            "counterAttackSameAmbit" integer,
            "postDestructionDamage" integer,
            "generatingRate" integer,
            "planetaryShieldContribution" integer,
            "oreMiningDifficulty" integer,
            "oreRefiningDifficulty" integer,
            "unguidedDefensiveSuccessRateNumerator" integer,
            "unguidedDefensiveSuccessRateDenominator" integer,
            "guidedDefensiveSuccessRateNumerator" integer,
            "guidedDefensiveSuccessRateDenominator" integer,
            "triggerRaidDefeatByDestruction" boolean,
            class text,
            "classAbbreviation" text,
            "defaultCosmeticModelNumber" text,
            "defaultCosmeticName" text
        );

        INSERT INTO structs.struct_type(
            id,
            type,
            category,
            build_limit ,
            build_difficulty,
            build_draw_p,
            max_health,
            passive_draw_p,
            possible_ambit,
            movable,
            slot_bound,
            primary_weapon,
            primary_weapon_control,
            primary_weapon_charge,
            primary_weapon_ambits,
            primary_weapon_targets,
            primary_weapon_shots,
            primary_weapon_damage,
            primary_weapon_blockable,
            primary_weapon_counterable,
            primary_weapon_armour_piercing,
            primary_weapon_recoil_damage,
            primary_weapon_shot_success_rate_numerator,
            primary_weapon_shot_success_rate_denominator,
            secondary_weapon,
            secondary_weapon_control,
            secondary_weapon_charge,
            secondary_weapon_ambits,
            secondary_weapon_targets,
            secondary_weapon_shots,
            secondary_weapon_damage,
            secondary_weapon_blockable,
            secondary_weapon_counterable,
            secondary_weapon_armour_piercing,
            secondary_weapon_recoil_damage,
            secondary_weapon_shot_success_rate_numerator,
            secondary_weapon_shot_success_rate_denominator,
            passive_weaponry,
            unit_defenses,
            ore_reserve_defenses,
            planetary_defenses,
            planetary_mining ,
            planetary_refinery,
            power_generation,
            activate_charge,
            build_charge,
            defend_change_charge,
            move_charge,
            stealth_activate_charge,
            attack_reduction,
            attack_counterable,
            stealth_systems,
            counter_attack,
            counter_attack_same_ambit,
            post_destruction_damage,
            generating_rate_p,
            planetary_shield_contribution,
            ore_mining_difficulty,
            ore_refining_difficulty,
            unguided_defensive_success_rate_numerator,
            unguided_defensive_success_rate_denominator,
            guided_defensive_success_rate_numerator,
            guided_defensive_success_rate_denominator,
            trigger_raid_defeat_by_destruction,
            updated_at,
            class,
            class_abbreviation,
            default_cosmetic_model_number,
            default_cosmetic_name,
            is_command
        )
        VALUES (
                       v.id,
                       v.type,

                       v.category,

                       v.build_limit,
                       v.build_difficulty,
                       v.build_draw,
                       v.max_health,
                       v.passive_draw,
                       v.possible_ambit,

                       v.movable,
                       v.slot_bound,


                       v.primary_weapon,
                       v.primary_weapon_control,
                       v.primary_weapon_charge,
                       v.primary_weapon_ambits,
                       v.primary_weapon_targets,
                       v.primary_weapon_shots,
                       v.primary_weapon_damage,
                       v.primary_weapon_blockable,
                       v.primary_weapon_counterable,
                       v.primary_weapon_armour_piercing,
                       v.primary_weapon_recoil_damage,
                       v.primary_weapon_shot_success_rate_numerator,
                       v.primary_weapon_shot_success_rate_denominator,

                       v.secondary_weapon,
                       v.secondary_weapon_control,
                       v.secondary_weapon_charge,
                       v.secondary_weapon_ambits,
                       v.secondary_weapon_targets,
                       v.secondary_weapon_shots,
                       v.secondary_weapon_damage,
                       v.secondary_weapon_blockable,
                       v.secondary_weapon_counterable,
                       v.secondary_weapon_armour_piercing,
                       v.secondary_weapon_recoil_damage,
                       v.secondary_weapon_shot_success_rate_numerator,
                       v.secondary_weapon_shot_success_rate_denominator,


                       v.passive_weaponry,
                       v.unit_defenses,
                       v.ore_reserve_defenses,
                       v.planetary_defenses,
                       v.planetary_mining,
                       v.planetary_refinery,
                       v.power_generation,

                       v.activate_charge,
                       v.build_charge,
                       v.defend_change_charge,
                       v.move_charge,
                       v.stealth_activate_charge,

                       v.attack_reduction,
                       v.attack_counterable,
                       v.stealth_systems,
                       v.counter_attack,
                       v.counter_attack_same_ambit,
                       v.post_destruction_damage,
                       v.generating_rate,
                       v.planetary_shield_contribution,
                       v.ore_mining_difficulty,
                       v.ore_refining_difficulty,

                       v.unguided_defensive_success_rate_numerator,
                       v.unguided_defensive_success_rate_denominator,

                       v.guided_defensive_success_rate_numerator,
                       v.guided_defensive_success_rate_denominator,

                       v.trigger_raid_defeat_by_destruction,

                       NOW(),
                       v.class,
                       v.class_abbreviation,
                       v.default_cosmetic_model_number,
                       v.default_cosmetic_name,
                       (v.class = 'Command Ship')
               ) ON CONFLICT (id) DO UPDATE
        SET
            type = EXCLUDED.type,
            category = EXCLUDED.category,
            build_limit = EXCLUDED.build_limit,
            build_difficulty = EXCLUDED.build_difficulty,
            build_draw_p = EXCLUDED.build_draw_p,
            max_health = EXCLUDED.max_health,
            passive_draw_p = EXCLUDED.passive_draw_p,
            possible_ambit = EXCLUDED.possible_ambit,
            movable = EXCLUDED.movable,
            slot_bound = EXCLUDED.slot_bound,
            primary_weapon = EXCLUDED.primary_weapon,
            primary_weapon_control = EXCLUDED.primary_weapon_control,
            primary_weapon_charge = EXCLUDED.primary_weapon_charge,
            primary_weapon_ambits = EXCLUDED.primary_weapon_ambits,
            primary_weapon_targets = EXCLUDED.primary_weapon_targets,
            primary_weapon_shots = EXCLUDED.primary_weapon_shots,
            primary_weapon_damage = EXCLUDED.primary_weapon_damage,
            primary_weapon_blockable = EXCLUDED.primary_weapon_blockable,
            primary_weapon_counterable = EXCLUDED.primary_weapon_counterable,
            primary_weapon_armour_piercing = EXCLUDED.primary_weapon_armour_piercing,
            primary_weapon_recoil_damage = EXCLUDED.primary_weapon_recoil_damage,
            primary_weapon_shot_success_rate_numerator = EXCLUDED.primary_weapon_shot_success_rate_numerator,
            primary_weapon_shot_success_rate_denominator = EXCLUDED.primary_weapon_shot_success_rate_denominator,
            secondary_weapon = EXCLUDED.secondary_weapon,
            secondary_weapon_control = EXCLUDED.secondary_weapon_control,
            secondary_weapon_charge = EXCLUDED.secondary_weapon_charge,
            secondary_weapon_ambits = EXCLUDED.secondary_weapon_ambits,
            secondary_weapon_targets = EXCLUDED.secondary_weapon_targets,
            secondary_weapon_shots = EXCLUDED.secondary_weapon_shots,
            secondary_weapon_damage = EXCLUDED.secondary_weapon_damage,
            secondary_weapon_blockable = EXCLUDED.secondary_weapon_blockable,
            secondary_weapon_counterable = EXCLUDED.secondary_weapon_counterable,
            secondary_weapon_armour_piercing = EXCLUDED.secondary_weapon_armour_piercing,
            secondary_weapon_recoil_damage = EXCLUDED.secondary_weapon_recoil_damage,
            secondary_weapon_shot_success_rate_numerator = EXCLUDED.secondary_weapon_shot_success_rate_numerator,
            secondary_weapon_shot_success_rate_denominator = EXCLUDED.secondary_weapon_shot_success_rate_denominator,
            passive_weaponry = EXCLUDED.passive_weaponry,
            unit_defenses = EXCLUDED.unit_defenses,
            ore_reserve_defenses = EXCLUDED.ore_reserve_defenses,
            planetary_defenses = EXCLUDED.planetary_defenses,
            planetary_mining = EXCLUDED.planetary_mining,
            planetary_refinery = EXCLUDED.planetary_refinery,
            power_generation = EXCLUDED.power_generation,
            activate_charge = EXCLUDED.activate_charge,
            build_charge = EXCLUDED.build_charge,
            defend_change_charge = EXCLUDED.defend_change_charge,
            move_charge = EXCLUDED.move_charge,
            stealth_activate_charge = EXCLUDED.stealth_activate_charge,
            attack_reduction = EXCLUDED.attack_reduction,
            attack_counterable = EXCLUDED.attack_counterable,
            stealth_systems = EXCLUDED.stealth_systems,
            counter_attack = EXCLUDED.counter_attack,
            counter_attack_same_ambit = EXCLUDED.counter_attack_same_ambit,
            post_destruction_damage = EXCLUDED.post_destruction_damage,
            generating_rate_p = EXCLUDED.generating_rate_p,
            planetary_shield_contribution = EXCLUDED.planetary_shield_contribution,
            ore_mining_difficulty = EXCLUDED.ore_mining_difficulty,
            ore_refining_difficulty = EXCLUDED.ore_refining_difficulty,
            unguided_defensive_success_rate_numerator = EXCLUDED.unguided_defensive_success_rate_numerator,
            unguided_defensive_success_rate_denominator = EXCLUDED.unguided_defensive_success_rate_denominator,
            guided_defensive_success_rate_numerator = EXCLUDED.guided_defensive_success_rate_numerator,
            guided_defensive_success_rate_denominator = EXCLUDED.guided_defensive_success_rate_denominator,
            trigger_raid_defeat_by_destruction = EXCLUDED.trigger_raid_defeat_by_destruction,
            updated_at = NOW(),
            class = EXCLUDED.class,
            class_abbreviation = EXCLUDED.class_abbreviation,
            default_cosmetic_model_number = EXCLUDED.default_cosmetic_model_number,
            default_cosmetic_name= EXCLUDED.default_cosmetic_name,
            is_command = EXCLUDED.is_command
        WHERE
            (
                structs.struct_type.type,
                structs.struct_type.category,
                structs.struct_type.build_limit,
                structs.struct_type.build_difficulty,
                structs.struct_type.build_draw_p,
                structs.struct_type.max_health,
                structs.struct_type.passive_draw_p,
                structs.struct_type.possible_ambit,
                structs.struct_type.movable,
                structs.struct_type.slot_bound,
                structs.struct_type.primary_weapon,
                structs.struct_type.primary_weapon_control,
                structs.struct_type.primary_weapon_charge,
                structs.struct_type.primary_weapon_ambits,
                structs.struct_type.primary_weapon_targets,
                structs.struct_type.primary_weapon_shots,
                structs.struct_type.primary_weapon_damage,
                structs.struct_type.primary_weapon_blockable,
                structs.struct_type.primary_weapon_counterable,
                structs.struct_type.primary_weapon_armour_piercing,
                structs.struct_type.primary_weapon_recoil_damage,
                structs.struct_type.primary_weapon_shot_success_rate_numerator,
                structs.struct_type.primary_weapon_shot_success_rate_denominator,
                structs.struct_type.secondary_weapon,
                structs.struct_type.secondary_weapon_control,
                structs.struct_type.secondary_weapon_charge,
                structs.struct_type.secondary_weapon_ambits,
                structs.struct_type.secondary_weapon_targets,
                structs.struct_type.secondary_weapon_shots,
                structs.struct_type.secondary_weapon_damage,
                structs.struct_type.secondary_weapon_blockable,
                structs.struct_type.secondary_weapon_counterable,
                structs.struct_type.secondary_weapon_armour_piercing,
                structs.struct_type.secondary_weapon_recoil_damage,
                structs.struct_type.secondary_weapon_shot_success_rate_numerator,
                structs.struct_type.secondary_weapon_shot_success_rate_denominator,
                structs.struct_type.passive_weaponry,
                structs.struct_type.unit_defenses,
                structs.struct_type.ore_reserve_defenses,
                structs.struct_type.planetary_defenses,
                structs.struct_type.planetary_mining,
                structs.struct_type.planetary_refinery,
                structs.struct_type.power_generation,
                structs.struct_type.activate_charge,
                structs.struct_type.build_charge,
                structs.struct_type.defend_change_charge,
                structs.struct_type.move_charge,
                structs.struct_type.stealth_activate_charge,
                structs.struct_type.attack_reduction,
                structs.struct_type.attack_counterable,
                structs.struct_type.stealth_systems,
                structs.struct_type.counter_attack,
                structs.struct_type.counter_attack_same_ambit,
                structs.struct_type.post_destruction_damage,
                structs.struct_type.generating_rate_p,
                structs.struct_type.planetary_shield_contribution,
                structs.struct_type.ore_mining_difficulty,
                structs.struct_type.ore_refining_difficulty,
                structs.struct_type.unguided_defensive_success_rate_numerator,
                structs.struct_type.unguided_defensive_success_rate_denominator,
                structs.struct_type.guided_defensive_success_rate_numerator,
                structs.struct_type.guided_defensive_success_rate_denominator,
                structs.struct_type.trigger_raid_defeat_by_destruction,
                structs.struct_type.class,
                structs.struct_type.class_abbreviation,
                structs.struct_type.default_cosmetic_model_number,
                structs.struct_type.default_cosmetic_name,
                structs.struct_type.is_command
            ) IS DISTINCT FROM (
                EXCLUDED.type,
                EXCLUDED.category,
                EXCLUDED.build_limit,
                EXCLUDED.build_difficulty,
                EXCLUDED.build_draw_p,
                EXCLUDED.max_health,
                EXCLUDED.passive_draw_p,
                EXCLUDED.possible_ambit,
                EXCLUDED.movable,
                EXCLUDED.slot_bound,
                EXCLUDED.primary_weapon,
                EXCLUDED.primary_weapon_control,
                EXCLUDED.primary_weapon_charge,
                EXCLUDED.primary_weapon_ambits,
                EXCLUDED.primary_weapon_targets,
                EXCLUDED.primary_weapon_shots,
                EXCLUDED.primary_weapon_damage,
                EXCLUDED.primary_weapon_blockable,
                EXCLUDED.primary_weapon_counterable,
                EXCLUDED.primary_weapon_armour_piercing,
                EXCLUDED.primary_weapon_recoil_damage,
                EXCLUDED.primary_weapon_shot_success_rate_numerator,
                EXCLUDED.primary_weapon_shot_success_rate_denominator,
                EXCLUDED.secondary_weapon,
                EXCLUDED.secondary_weapon_control,
                EXCLUDED.secondary_weapon_charge,
                EXCLUDED.secondary_weapon_ambits,
                EXCLUDED.secondary_weapon_targets,
                EXCLUDED.secondary_weapon_shots,
                EXCLUDED.secondary_weapon_damage,
                EXCLUDED.secondary_weapon_blockable,
                EXCLUDED.secondary_weapon_counterable,
                EXCLUDED.secondary_weapon_armour_piercing,
                EXCLUDED.secondary_weapon_recoil_damage,
                EXCLUDED.secondary_weapon_shot_success_rate_numerator,
                EXCLUDED.secondary_weapon_shot_success_rate_denominator,
                EXCLUDED.passive_weaponry,
                EXCLUDED.unit_defenses,
                EXCLUDED.ore_reserve_defenses,
                EXCLUDED.planetary_defenses,
                EXCLUDED.planetary_mining,
                EXCLUDED.planetary_refinery,
                EXCLUDED.power_generation,
                EXCLUDED.activate_charge,
                EXCLUDED.build_charge,
                EXCLUDED.defend_change_charge,
                EXCLUDED.move_charge,
                EXCLUDED.stealth_activate_charge,
                EXCLUDED.attack_reduction,
                EXCLUDED.attack_counterable,
                EXCLUDED.stealth_systems,
                EXCLUDED.counter_attack,
                EXCLUDED.counter_attack_same_ambit,
                EXCLUDED.post_destruction_damage,
                EXCLUDED.generating_rate_p,
                EXCLUDED.planetary_shield_contribution,
                EXCLUDED.ore_mining_difficulty,
                EXCLUDED.ore_refining_difficulty,
                EXCLUDED.unguided_defensive_success_rate_numerator,
                EXCLUDED.unguided_defensive_success_rate_denominator,
                EXCLUDED.guided_defensive_success_rate_numerator,
                EXCLUDED.guided_defensive_success_rate_denominator,
                EXCLUDED.trigger_raid_defeat_by_destruction,
                EXCLUDED.class,
                EXCLUDED.class_abbreviation,
                EXCLUDED.default_cosmetic_model_number,
                EXCLUDED.default_cosmetic_name,
                EXCLUDED.is_command
            );
    END
    $BODY$
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER
    COST 100;

COMMIT;
