-- Deploy structs-pg:table-struct-type to pg

BEGIN;

CREATE UNLOGGED TABLE struct_type (
    id INTEGER PRIMARY KEY,
    type CHARACTER VARYING,
    category CHARACTER VARYING,
    build_limit INTEGER,
    build_difficulty INTEGER,
    build_draw INTEGER,
    max_health INTEGER,
    passive_draw INTEGER,
    possible_ambit INTEGER,
    movable boolean,
    slot_bound boolean,
    primary_weapon CHARACTER VARYING,
    primary_weapon_control CHARACTER VARYING,
    primary_weapon_charge INTEGER,
    primary_weapon_ambits INTEGER,
    primary_weapon_targets INTEGER,
    primary_weapon_shots INTEGER,
    primary_weapon_damage INTEGER,
    primary_weapon_blockable boolean,
    primary_weapon_counterable boolean,
    primary_weapon_recoil_damage INTEGER,
    primary_weapon_shot_success_rate_numerator INTEGER,
    primary_weapon_shot_success_rate_denominator INTEGER,
    secondary_weapon CHARACTER VARYING,
    secondary_weapon_control CHARACTER VARYING,
    secondary_weapon_charge INTEGER,
    secondary_weapon_ambits INTEGER,
    secondary_weapon_targets INTEGER,
    secondary_weapon_shots INTEGER,
    secondary_weapon_damage INTEGER,
    secondary_weapon_blockable boolean,
    secondary_weapon_counterable boolean,
    secondary_weapon_recoil_damage INTEGER,
    secondary_weapon_shot_success_rate_numerator INTEGER,
    secondary_weapon_shot_success_rate_denominator INTEGER,
    passive_weaponry CHARACTER VARYING,
    unit_defenses CHARACTER VARYING,
    ore_reserve_defenses CHARACTER VARYING,
    planetary_defenses CHARACTER VARYING,
    planetary_mining CHARACTER VARYING,
    planetary_refinery CHARACTER VARYING,
    power_generation CHARACTER VARYING,
    activate_charge INTEGER,
    build_charge INTEGER,
    defend_change_charge INTEGER,
    move_charge INTEGER,
    ore_mining_charge INTEGER,
    ore_refining_charge INTEGER,
    stealth_activate_charge INTEGER,
    attack_reduction INTEGER,
    attack_counterable boolean,
    stealth_systems boolean,
    counter_attack INTEGER,
    counter_attack_same_ambit INTEGER,
    post_destruction_damage INTEGER,
    generating_rate INTEGER,
    planetary_shield_contribution INTEGER,
    ore_mining_difficulty INTEGER,
    ore_refining_difficulty INTEGER,
    unguided_defensive_success_rate_numerator INTEGER,
    unguided_defensive_success_rate_denominator INTEGER,
    guided_defensive_success_rate_numerator INTEGER,
    guided_defensive_success_rate_denominator INTEGER,
    trigger_raid_defeat_by_destruction boolean,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE structs.struct_type_meta (
    id INTEGER PRIMARY KEY,
    name CHARACTER VARYING,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


COMMIT;
