-- Deploy structs-pg:view-struct-20251121-add-is-command-to-struct-type to pg

BEGIN;

    DROP VIEW view.struct;

    CREATE OR REPLACE VIEW view.struct AS
        SELECT
            struct.id as struct_id,
            index,

            location_type,
            location_id,
            operating_ambit,
            slot,

            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='0-' || struct.id),0) as  health,
            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='1-' || struct.id),0) as  status,

            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='2-' || struct.id),0) as  block_start_build,
            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='3-' || struct.id),0) as  block_start_ore_mine,
            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='4-' || struct.id),0) as  block_start_ore_refine,

            COALESCE((SELECT struct_attribute.val FROM structs.struct_attribute WHERE struct_attribute.id='5-' || struct.id),0) as  protected_struct_index,

            COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='1-' || struct.id),0) as generator_fuel_p,
            floor(COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='1-' || struct.id),0)/1000000) as generator_fuel,

            COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='3-' || struct.id),0) as generator_load_p,
            floor(COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='3-' || struct.id),0)/1000) as generator_load,

            COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='2-' || struct.id),0) as generator_capacity_p,
            floor(COALESCE((SELECT grid.val FROM structs.grid WHERE grid.id='2-' || struct.id),0)/1000) as generator_capacity,

            struct_type.id as struct_type_id,
            struct_type.type,
            struct_type.category,
            struct_type.class,
            struct_type.class_abbreviation,
            struct_type.is_command,
            struct_type.default_cosmetic_model_number,
            struct_type.default_cosmetic_name,
            struct_type.build_limit,
            struct_type.build_difficulty,
            struct_type.build_draw,
            struct_type.build_draw_p,
            struct_type.max_health,
            struct_type.passive_draw,
            struct_type.passive_draw_p,
            struct_type.possible_ambit_array,
            struct_type.possible_ambit,
            struct_type.movable,
            struct_type.slot_bound,
            struct_type.primary_weapon,
            struct_type.primary_weapon_control,
            struct_type.primary_weapon_charge,
            struct_type.primary_weapon_ambits,
            struct_type.primary_weapon_ambits_array,
            struct_type.primary_weapon_targets,
            struct_type.primary_weapon_shots,
            struct_type.primary_weapon_damage,
            struct_type.primary_weapon_blockable,
            struct_type.primary_weapon_counterable,
            struct_type.primary_weapon_recoil_damage,
            struct_type.primary_weapon_shot_success_rate_numerator,
            struct_type.primary_weapon_shot_success_rate_denominator,
            struct_type.secondary_weapon,
            struct_type.secondary_weapon_control,
            struct_type.secondary_weapon_charge,
            struct_type.secondary_weapon_ambits,
            struct_type.secondary_weapon_ambits_array,
            struct_type.secondary_weapon_targets,
            struct_type.secondary_weapon_shots,
            struct_type.secondary_weapon_damage,
            struct_type.secondary_weapon_blockable,
            struct_type.secondary_weapon_counterable,
            struct_type.secondary_weapon_recoil_damage,
            struct_type.secondary_weapon_shot_success_rate_numerator,
            struct_type.secondary_weapon_shot_success_rate_denominator,
            struct_type.passive_weaponry,
            struct_type.unit_defenses,
            struct_type.ore_reserve_defenses,
            struct_type.planetary_defenses,
            struct_type.planetary_mining,
            struct_type.planetary_refinery,
            struct_type.power_generation,
            struct_type.activate_charge,
            struct_type.build_charge,
            struct_type.defend_change_charge,
            struct_type.move_charge,
            struct_type.stealth_activate_charge,
            struct_type.attack_reduction,
            struct_type.attack_counterable,
            struct_type.stealth_systems,
            struct_type.counter_attack,
            struct_type.counter_attack_same_ambit,
            struct_type.post_destruction_damage,
            struct_type.generating_rate,
            struct_type.planetary_shield_contribution,
            struct_type.ore_mining_difficulty,
            struct_type.ore_refining_difficulty,
            struct_type.unguided_defensive_success_rate_numerator,
            struct_type.unguided_defensive_success_rate_denominator,
            struct_type.guided_defensive_success_rate_numerator,
            struct_type.guided_defensive_success_rate_denominator,
            struct_type.trigger_raid_defeat_by_destruction,
            struct_type.updated_at,

            struct.creator,
            struct.owner,
            struct.created_at as struct_created_at,
            struct.updated_at as struct_updated_at
        FROM structs.struct, structs.struct_type
        WHERE struct_type.id = struct.type;

COMMIT;
