-- Revert structs-pg:function-unit-display-format from pg

BEGIN;

DROP FUNCTION IF EXISTS structs.UNIT_DISPLAY_FORMAT(NUMERIC, TEXT);
DROP FUNCTION IF EXISTS structs.UNIT_LEGACY_FORMAT(NUMERIC, TEXT);

COMMIT;
