-- Revert structs-pg:table-signer-account from pg

BEGIN;

DROP FUNCTION IF EXISTS signer.CLAIM_INTERNAL_ACCOUNT(tx_id INTEGER);
DROP FUNCTION IF EXISTS signer.UPDATE_PENDING_ACCOUNT(_account_id INTEGER, _player_id CHARACTER VARYING, _address CHARACTER VARYING, _pubkey CHARACTER VARYING, _signature CHARACTER VARYING, _permission INTEGER);
DROP FUNCTION IF EXISTS signer.CREATE_PENDING_ACCOUNT_FROM_ROLE(_role_id INTEGER, _address CHARACTER VARYING);
DROP FUNCTION IF EXISTS signer.GET_NEW_ACCOUNT();
DROP FUNCTION IF EXISTS signer.LOAD_INTERNAL_ACCOUNTS(account_set JSONB, default_role_id CHARACTER VARYING);
DROP FUNCTION IF EXISTS signer.LOAD_ACCOUNT(_address CHARACTER VARYING);
DROP TABLE IF EXISTS signer.account CASCADE;
DROP TYPE IF EXISTS structs.signer_account_status;

COMMIT;
