-- Revert structs-pg:table-signer-role from pg

BEGIN;

DROP FUNCTION IF EXISTS signer.CREATE_SYSTEM_ROLE(_username CHARACTER VARYING, _guild_id CHARACTER VARYING, _address CHARACTER VARYING);
DROP FUNCTION IF EXISTS signer.CLAIM_ROLE_STUB();
DROP FUNCTION IF EXISTS signer.SET_PLAYER_INTERNAL_PENDING_PRIMARY_ADDRESS(_role_id INTEGER, _primary_address CHARACTER VARYING);
DROP TABLE IF EXISTS signer.role CASCADE;
DROP TYPE IF EXISTS structs.signer_role_status;

COMMIT;
