-- Revert structs-pg:trigger-grass-guild from pg

BEGIN;

DROP TRIGGER IF EXISTS GUILD_NOTIFY ON structs.guild;
DROP TRIGGER IF EXISTS GUILD_META_NOTIFY ON structs.guild_meta;
DROP TRIGGER IF EXISTS GUILD_MEMBERSHIP_NOTIFY ON structs.guild_membership_application;
DROP FUNCTION IF EXISTS structs.GUILD_NOTIFY();
DROP FUNCTION IF EXISTS structs.GUILD_META_NOTIFY();
DROP FUNCTION IF EXISTS structs.GUILD_MEMBERSHIP_NOTIFY();

COMMIT;
