-- Revert structs-pg:trigger-player-pending from pg

BEGIN;

DROP TRIGGER IF EXISTS PLAYER_PENDING_MERGE ON structs.player;
DROP TRIGGER IF EXISTS PLAYER_INTERNAL_PENDING ON structs.player_internal_pending;
DROP TRIGGER IF EXISTS PLAYER_PENDING_JOIN_PROXY ON structs.player_pending;
DROP TRIGGER IF EXISTS PLAYER_ADDRESS_PENDING_MERGE ON structs.player_address;
DROP FUNCTION IF EXISTS structs.PLAYER_PENDING_MERGE();
DROP FUNCTION IF EXISTS structs.PLAYER_INTERNAL_PENDING();
DROP FUNCTION IF EXISTS structs.PLAYER_PENDING_JOIN_PROXY();
DROP FUNCTION IF EXISTS structs.PLAYER_ADDRESS_PENDING_MERGE();

COMMIT;
