-- Revert structs-pg:trigger-grass-player from pg

BEGIN;

DROP TRIGGER IF EXISTS PLAYER_NOTIFY ON structs.player;
DROP TRIGGER IF EXISTS PLAYER_META_NOTIFY ON structs.player_meta;
DROP TRIGGER IF EXISTS PLAYER_ADDRESS_NOTIFY ON structs.player_address;
DROP TRIGGER IF EXISTS PLAYER_ADDRESS_PENDING_NOTIFY ON structs.player_address_pending;
DROP FUNCTION IF EXISTS structs.PLAYER_NOTIFY();
DROP FUNCTION IF EXISTS structs.PLAYER_META_NOTIFY();
DROP FUNCTION IF EXISTS structs.PLAYER_ADDRESS_NOTIFY();
DROP FUNCTION IF EXISTS structs.PLAYER_ADDRESS_PENDING_NOTIFY();

COMMIT;
